spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: person-user-ms
          uri: lb://PERSON-USER-MS
          predicates:
            - Path=/api/v1/customers/**

        - id: transaction-account-ms
          uri: lb://TRANSACTION-ACCOUNT-MS
          predicates:
            - Path=/api/v1/accounts/**, /api/v1/movements/**

        - id: discovery-server
          uri: lb://DISCOVERY-SERVER
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: lb://DISCOVERY-SERVER-STATIC
          predicates:
            - Path=/eureka/**

    loadbalancer:
      ribbon:
        enabled: false
